### ISSUE TITLE
Can not reproduce the result?

### ISSUE THREAD

**Issue by ClementFYJ** [xihongyang1999/DealMVC#1]
Hi Xihong,

Wonderful work!

Just want to check whether the network illustrated is the final model? When I retrain it on my computer, the acc achieved is 0.62 which is far from the pth you provided. Is there any implementation of model that have not been released yet? Or are there other issues I should pay attention to? Hope you can provide some advice, thank you.

**Comment by xihongyang1999** [comment]
Hi, thank you for your attention. Please strictly match the version of the package in our published requirements. In addition, our experimental environment is Intel Core i7-7820x CPU, NVIDIA GeForce RTX 3080 GPU, and 64GB RAM. We have found that the results may fluctuate due to differences in equipment. Therefore, in order to quickly validate our model, we have released the pth of the relevant models. You can run test. py to verify the results.
